language: cpp
cache: ccache
before_install:
  - sudo apt-get install -y libeigen3-dev python-matplotlib python-numpy python2.7-dev libopencv-dev
addons:
  apt:
    update: true
    packages: 
      - cmake
      - cmake-data
script: mkdir build && cd build && cmake .. && make && sudo make install